---
title: "problems with cart"
output:
  html_document:
    df_print: paged
  pdf_document: default
date: "2024-07-18"
urlcolor: blue
---

```{r setup, warning=FALSE, message=FALSE}

 # Set the global seed here
# knitr::opts_chunk$set(echo = TRUE)
set.seed(12345)

# load libraries
library(tidyverse)
library(synthpop)
```

# Generate simulated data
```{r,echo=FALSE}

# Number of observations
n <- 1000

# Define the 16 possible combinations of four binary variables
combinations <- expand.grid(y1 = c(0, 1), y2 = c(0, 1), y3 = c(0, 1), y4 = c(0, 1))

# Define c_16 and C_−16
c_16 <- combinations[16,]
C_minus_16 <- combinations[-16,]

# Initialize the dataset
D <- data.frame(matrix(ncol = 4, nrow = n))
colnames(D) <- c("var1", "var2", "var3", "var4")

# Sample the first 999 observations from C_minus_16 with equal probability
for (i in 1:(n-1)) {
  sampled_row <- sample(1:15, 1)
  D[i,] <- C_minus_16[sampled_row,]
}

# Set the 1000th observation to c_16
D[1000,] <- c_16

# Convert to data frame and print the first few rows
df_ods <- as.data.frame(D)

rm(D,c_16,C_minus_16,combinations)

ods <- df_ods

# Create a frequency table
ods$combine <- paste(ods$var1, ods$var2, ods$var3, ods$var4, sep = "")

ods <- ods %>%
  select(-matches("var"))
frequency <- as.data.frame(table(ods))
print(frequency)

ggplot(frequency, aes(x = combine, y = Freq)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width=unit(1, "cm"),
        axis.title.x = element_blank(),
        axis.line.y = element_line(color="black", linewidth=.5),
        axis.line.x = element_line(color="black", linewidth=.5)
  )
```

# Generate synthetic data (default values)

```{r, echo=FALSE}
sds <- syn(df_ods, m=1)
sds <- sds$syn

# Create a frequency table
sds$combine <- paste(sds$var1, sds$var2, sds$var3, sds$var4, sep = "")
sds <- sds %>%
  select(-matches("var"))
frequency <- as.data.frame(table(sds))

ggplot(frequency, aes(x = combine, y = Freq)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width=unit(1, "cm"),
        axis.title.x = element_blank(),
        axis.line.y = element_line(color="black", linewidth=.5),
        axis.line.x = element_line(color="black", linewidth=.5)
  )
```

# Generate synthetic data with minimum values
```{r, echo=FALSE}
sds <- syn(df_ods, m=1, minnumlevels = 5)
sds <- sds$syn

# Create a frequency table
sds$combine <- paste(sds$var1, sds$var2, sds$var3, sds$var4, sep = "")
sds <- sds %>%
  select(-matches("var"))
frequency <- as.data.frame(table(sds))

ggplot(frequency, aes(x = combine, y = Freq)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width=unit(1, "cm"),
        axis.title.x = element_blank(),
        axis.line.y = element_line(color="black", linewidth=.5),
        axis.line.x = element_line(color="black", linewidth=.5)
  )
```


# Generate synthetic data with minimum values with ctree
```{r, echo=FALSE}
sds <- syn(df_ods, m=1, minnumlevels = 5, method = "ctree")
sds <- sds$syn

# Create a frequency table
sds$combine <- paste(sds$var1, sds$var2, sds$var3, sds$var4, sep = "")
sds <- sds %>%
  select(-matches("var"))
frequency <- as.data.frame(table(sds))

ggplot(frequency, aes(x = combine, y = Freq)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width=unit(1, "cm"),
        axis.title.x = element_blank(),
        axis.line.y = element_line(color="black", linewidth=.5),
        axis.line.x = element_line(color="black", linewidth=.5)
  )
```

# Generate synthetic data with ctree
```{r, echo=FALSE}
sds <- syn(df_ods, m=1, method = "ctree")
sds <- sds$syn

# Create a frequency table
sds$combine <- paste(sds$var1, sds$var2, sds$var3, sds$var4, sep = "")
sds <- sds %>%
  select(-matches("var"))
frequency <- as.data.frame(table(sds))

ggplot(frequency, aes(x = combine, y = Freq)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.key.width=unit(1, "cm"),
        axis.title.x = element_blank(),
        axis.line.y = element_line(color="black", linewidth=.5),
        axis.line.x = element_line(color="black", linewidth=.5)
  )
```
